#LVAI-25 Card CRUD completed.
dovlaper/ToDo_laravel_ft_react pull request #4
Opened 2018-11-08 10:38 UTC by dovlaper

2018-11-08 11:31 UTC, AlexSensei requested changes

2018-11-08 11:31 UTC, AlexSensei commented on toDoApp/app/Http/Controllers/CardsController.php
> +        $cards = Card::where('user_id',auth()->user()->id )->get();
Razmak posle zareza, i razmak na kraju je suvisan

2018-11-08 11:31 UTC, AlexSensei commented on toDoApp/app/Http/Controllers/CardsController.php
> +        return response($cards,200);
razmak posle zareza i umesto 200 koristi HTTP_OK

2018-11-08 11:31 UTC, AlexSensei commented on toDoApp/app/Http/Controllers/CardsController.php
> +        return response($card, 200);
HTTP_OK

2018-11-08 11:31 UTC, AlexSensei commented on toDoApp/app/Http/Controllers/CardsController.php
> +        }    }
Format?

2018-11-08 11:31 UTC, AlexSensei commented on toDoApp/app/Http/Controllers/CardsController.php
> +            return response($card,200);
Razmak posle ,

2018-11-08 11:31 UTC, AlexSensei commented on toDoApp/app/Model/Card.php
> +        'title', 'content','user_id','done','priority'
Razmaci

2018-11-08 11:31 UTC, AlexSensei commented on toDoApp/database/seeds/UsersTableSeeder.php
> +            'done' =>false
razmak posle => i svuda dole u kodu

2018-11-08 11:31 UTC, AlexSensei commented on toDoApp/app/Http/Controllers/CardsController.php
> +        if($card->user_id == auth()->user()->id)
kod if-a { se pisu u istom redu znaci if(true) { npr

2018-11-08 11:31 UTC, AlexSensei commented on toDoApp/app/Http/Controllers/CardsController.php
> +            return response($card,200);
razmak i formatiraj ovaj if

2018-11-08 11:31 UTC, AlexSensei commented on toDoApp/app/Http/Controllers/CardsController.php
> +    public function getCard(Card $card){
{ u novi red

2018-11-08 11:31 UTC, AlexSensei commented on toDoApp/app/Http/Controllers/CardsController.php
> +            return response($card , 200);
razmak viska pre ,

2018-11-08 11:31 UTC, AlexSensei commented on toDoApp/app/Http/Controllers/CardsController.php
> +        if($card->user_id == auth()->user()->id)
formatiraj if i imas gore jedan space viska posle $card

2018-11-08 11:31 UTC, AlexSensei commented on toDoApp/app/Http/Controllers/CardsController.php
> +            $card->delete();
Ajde implementira SoftDelete :)

2018-11-08 12:57 UTC, AlexSensei commented on toDoApp/app/Http/Controllers/CardsController.php
> +            return response($card, 403);
403?

2018-11-08 12:57 UTC, AlexSensei commented on toDoApp/app/Http/Controllers/CardsController.php
> +            return response($card, 403);
403

2018-11-09 06:54 UTC, AlexSensei requested changes

2018-11-09 06:54 UTC, AlexSensei commented on toDoApp/app/Model/Card.php
> +        'title', 'content','user_id','done','priority'
Opet razmaci

2018-11-09 06:54 UTC, AlexSensei commented on toDoApp/database/seeds/UsersTableSeeder.php
> +                'title' =>$faker->sentence,
razmak

2018-11-09 06:54 UTC, AlexSensei commented on toDoApp/app/Http/Controllers/CardsController.php
> +            return response($card, HTTP_FORBIDDEN);
Jesi siguran da ce ovo da radi bez Response:: ?

2018-11-10 18:54 UTC, miljanic requested changes

2018-11-10 18:54 UTC, Pseudonick47 commented on toDoApp/database/seeds/UsersTableSeeder.php
> +        DB::table('users')->insert([
Koristi 
`User::create(...)`
on ti vraca usera ako ti zatreba negde kasnije u siderima, a i postavlja `created_at` i `updated_at` automatski

2018-11-10 18:54 UTC, Pseudonick47 commented on toDoApp/database/migrations/2018_11_07_122822_create_cards_table.php
> +            $table->integer('user_id');
Ovo je foreign key, dodaj to
https://laravel.com/docs/5.7/migrations#foreign-key-constraints

2018-11-10 18:54 UTC, Pseudonick47 commented on toDoApp/app/Http/Controllers/CardsController.php
> +            $card->delete();
mozes koristiti `auth()->id()`, krace je

2018-11-10 18:54 UTC, Pseudonick47 commented on toDoApp/app/Http/Controllers/CardsController.php
> +            return response($card, Response::HTTP_OK);
kad radis delete (uglavnom) nema potrebe vracati taj objekat, mozes samo da vratis 204 status kod

2018-11-10 18:54 UTC, Pseudonick47 commented on toDoApp/app/Http/Controllers/CardsController.php
> +            return response($card, Response::HTTP_FORBIDDEN);
Autorizaciju izvuci ili u Policy ili u request (preporucujem policy, mada ovde nema neke razlike)

2018-11-10 18:54 UTC, Pseudonick47 commented on toDoApp/app/Http/Controllers/CardsController.php
> +            return response($card, Response::HTTP_FORBIDDEN);
U policy/request

2018-11-10 18:54 UTC, Pseudonick47 commented on toDoApp/app/Http/Controllers/CardsController.php
> +            return response($card, Response::HTTP_FORBIDDEN);
U policy/request

2018-11-10 18:54 UTC, Pseudonick47 commented on toDoApp/app/Http/Controllers/CardsController.php
> +        return response($card, Response::HTTP_OK);
Ako vec rucno setujes status code onda stavi onaj koji treba 😂 
201 je za created

2018-11-10 18:54 UTC, Pseudonick47 commented on toDoApp/app/Http/Controllers/CardsController.php
> +        $cards = Card::where('user_id', auth()->user()->id)->get();
napravio si relaciju `cards()` na useru, ovde treba to da koristis
znaci:
`auth()->user()->cards`
`auth()->user()->cards()` ti je query builder ukoliko hoces jos po necemu da filtriras, sortiras ili sta god na sql nivou a 
`auth()->user()->cards` ti izvrsi taj query, kao da si rekao `auth()->user()->cards()->get()`

2018-11-11 00:02 UTC, merged